org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric 版本信息：https://fabricmc.net/develop
minecraft_version=1.20.4
yarn_mappings=1.20.4+build.3
loader_version=0.19.5
loom_version=1.11.8

# Mod 信息
mod_version=1.1.0
maven_group=com.syyann.phantomcreeper
archives_base_name=phantom-creeper

# 依赖
fabric_version=0.97.3+1.20.4
